- childrenSearchable: 0
  code: feelingReportPos
  keywords: ''
  parentCode: root
  positive: true
  searchable: true
  sort: 0
  text: Positive Feeling
- childrenSearchable: 0
  code: feelingReportNeg
  keywords: ''
  parentCode: root
  positive: false
  searchable: true
  sort: 0
  text: Negative Feeling
- childrenSearchable: 0
  code: communicationPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 1
  text: Communication
- childrenSearchable: 0
  code: commClearPos
  keywords: ''
  parentCode: communicationPos
  positive: true
  searchable: 0
  sort: 1
  text: Effective
- childrenSearchable: 0
  code: commProactivePos
  keywords: ''
  parentCode: communicationPos
  positive: true
  searchable: 0
  sort: 2
  text: Proactive
- childrenSearchable: 0
  code: commRespectfulPos
  keywords: ''
  parentCode: communicationPos
  positive: true
  searchable: 0
  sort: 3
  text: Respectful
- childrenSearchable: 0
  code: communicationNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 1
  text: Communication
- childrenSearchable: 0
  code: commClearNeg
  keywords: ''
  parentCode: communicationNeg
  positive: false
  searchable: 0
  sort: 1
  text: Confusing
- childrenSearchable: 0
  code: commProactiveNeg
  keywords: ''
  parentCode: communicationNeg
  positive: false
  searchable: 0
  sort: 2
  text: Not Happening
- childrenSearchable: 0
  code: commRespectfulNeg
  keywords: ''
  parentCode: communicationNeg
  positive: false
  searchable: 0
  sort: 3
  text: Disrespectful
- childrenSearchable: 0
  code: compatPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 2
  text: Lifestyle
- childrenSearchable: 0
  code: compatHabitsPos
  keywords: ''
  parentCode: compatPos
  positive: true
  searchable: 0
  sort: 1
  text: Habits I Like
- childrenSearchable: 0
  code: compatAppearancePos
  keywords: ''
  parentCode: compatPos
  positive: true
  searchable: 0
  sort: 2
  text: Desirable Appearance
- childrenSearchable: 0
  code: compatAvailabilityPos
  keywords: ''
  parentCode: compatPos
  positive: true
  searchable: 0
  sort: 3
  text: Available / Allows Space
- childrenSearchable: 0
  code: compatHealthPos
  keywords: ''
  parentCode: compatPos
  positive: true
  searchable: 0
  sort: 4
  text: Healthy Diet / Good Fitness
- childrenSearchable: 0
  code: compatNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 2
  text: Lifestyle
- childrenSearchable: 0
  code: compatHabitsNeg
  keywords: ''
  parentCode: compatNeg
  positive: false
  searchable: 0
  sort: 1
  text: Habits I Don`t Like
- childrenSearchable: 0
  code: compatAppearanceNeg
  keywords: ''
  parentCode: compatNeg
  positive: false
  searchable: 0
  sort: 2
  text: Undesirable Appearance
- childrenSearchable: 0
  code: compatAvailabilityNeg
  keywords: ''
  parentCode: compatNeg
  positive: false
  searchable: 0
  sort: 3
  text: Unavailable / Too Available
- childrenSearchable: 0
  code: compatHealthNeg
  keywords: ''
  parentCode: compatNeg
  positive: false
  searchable: 0
  sort: 4
  text: Poor Diet / Poor Fitness
- childrenSearchable: 0
  code: famPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 3
  text: Family & Friends
- childrenSearchable: 0
  code: famFamPos
  keywords: ''
  parentCode: famPos
  positive: true
  searchable: 0
  sort: 1
  text: Positives on Family / Friends
- childrenSearchable: 0
  code: famChildPos
  keywords: ''
  parentCode: famPos
  positive: true
  searchable: 0
  sort: 2
  text: Positives on Children
- childrenSearchable: 0
  code: famNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 3
  text: Family & Friends
- childrenSearchable: 0
  code: famFamNeg
  keywords: ''
  parentCode: famNeg
  positive: false
  searchable: 0
  sort: 1
  text: Negatives on Family / Friends
- childrenSearchable: 0
  code: famChildNeg
  keywords: ''
  parentCode: famNeg
  positive: false
  searchable: 0
  sort: 2
  text: Negatives on Children
- childrenSearchable: 0
  code: financialPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 4
  text: Finances
- childrenSearchable: 0
  code: finaReliablePos
  keywords: ''
  parentCode: financialPos
  positive: true
  searchable: 0
  sort: 1
  text: Responsible / Smart
- childrenSearchable: 0
  code: finaSharingPos
  keywords: ''
  parentCode: financialPos
  positive: true
  searchable: 0
  sort: 2
  text: Generous / Sharing
- childrenSearchable: 0
  code: financialNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 4
  text: Finances
- childrenSearchable: 0
  code: finaReliableNeg
  keywords: ''
  parentCode: financialNeg
  positive: false
  searchable: 0
  sort: 1
  text: Irresponsible / Unwise
- childrenSearchable: 0
  code: finaSharingNeg
  keywords: ''
  parentCode: financialNeg
  positive: false
  searchable: 0
  sort: 2
  text: Stingy / Selfish
- childrenSearchable: 0
  code: sexPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 5
  text: Intimacy
- childrenSearchable: 0
  code: sexOpenPos
  keywords: ''
  parentCode: sexPos
  positive: true
  searchable: 0
  sort: 1
  text: Good Connection
- childrenSearchable: 0
  code: sexQualityPos
  keywords: ''
  parentCode: sexPos
  positive: true
  searchable: 0
  sort: 2
  text: Frequent / Passionate
- childrenSearchable: 0
  code: sexNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 5
  text: Intimacy
- childrenSearchable: 0
  code: sexOpenNeg
  keywords: ''
  parentCode: sexNeg
  positive: false
  searchable: 0
  sort: 1
  text: Bad Connection
- childrenSearchable: 0
  code: sexQualityNeg
  keywords: ''
  parentCode: sexNeg
  positive: false
  searchable: 0
  sort: 2
  text: Infrequent / Boring
- childrenSearchable: 0
  code: respectPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 6
  text: Respect
- childrenSearchable: 0
  code: respConsideratePos
  keywords: ''
  parentCode: respectPos
  positive: true
  searchable: 0
  sort: 1
  text: Considerate / Kind
- childrenSearchable: 0
  code: respAttentivePos
  keywords: ''
  parentCode: respectPos
  positive: true
  searchable: 0
  sort: 2
  text: Good Attention / Empathetic
- childrenSearchable: 0
  code: respSensitivePos
  keywords: ''
  parentCode: respectPos
  positive: true
  searchable: 0
  sort: 3
  text: Good Boundaries
- childrenSearchable: 0
  code: respectNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 6
  text: 'Respect '
- childrenSearchable: 0
  code: respConsiderateNeg
  keywords: ''
  parentCode: respectNeg
  positive: false
  searchable: 0
  sort: 1
  text: Inconsiderate / Rude
- childrenSearchable: 0
  code: respAttentiveNeg
  keywords: ''
  parentCode: respectNeg
  positive: false
  searchable: 0
  sort: 2
  text: Poor Attention / Insensitive
- childrenSearchable: 0
  code: respSensitiveNeg
  keywords: ''
  parentCode: respectNeg
  positive: false
  searchable: 0
  sort: 3
  text: Poor Boundaries
- childrenSearchable: 0
  code: trustPos
  keywords: ''
  parentCode: ''
  positive: true
  searchable: 0
  sort: 7
  text: Trust
- childrenSearchable: 0
  code: trusHonestPos
  keywords: ''
  parentCode: trustPos
  positive: true
  searchable: 0
  sort: 1
  text: Honest / Ethical
- childrenSearchable: 0
  code: trusReliablePos
  keywords: ''
  parentCode: trustPos
  positive: true
  searchable: 0
  sort: 2
  text: Dependable / Supportive
- childrenSearchable: 0
  code: trusSafePos
  keywords: ''
  parentCode: trustPos
  positive: true
  searchable: 0
  sort: 3
  text: Safe / Secure
- childrenSearchable: 0
  code: trustNeg
  keywords: ''
  parentCode: ''
  positive: false
  searchable: 0
  sort: 7
  text: Trust
- childrenSearchable: 0
  code: trusHonestNeg
  keywords: ''
  parentCode: trustNeg
  positive: false
  searchable: 0
  sort: 1
  text: Dishonest / Unethical
- childrenSearchable: 0
  code: trusReliableNeg
  keywords: ''
  parentCode: trustNeg
  positive: false
  searchable: 0
  sort: 2
  text: Undependable / Unsupportive
- childrenSearchable: 0
  code: trusSafeNeg
  keywords: ''
  parentCode: trustNeg
  positive: false
  searchable: 0
  sort: 3
  text: Unsafe / Insecure
